export const environment = {
  production: false,
  environment: 'Dev',
  baseServiceURL: '',
  googleMapsApiKey: 'AIzaSyBrxrArxmCCNdXeWWyCZUwH42gb6p7iqK4',
  bypassGoogle: false,
  apiUrl: 'https://api.demo.solarfast.co.uk/v1',
  originUrl: 'https://solarfast.co.uk/postcode/',
  productImageFallback: 'https://solarfast.blob.core.windows.net/solarfast/files/logo-200.png',
  contactNumber: '0330 818 3116',
  contactNumberSales: '01977 803501',
  contactEmail: 'contact@solarfast.co.uk',
  singleLineBusinessAddress: 'Unit 17, Allerton Bywater Network Centre, Letchmire Rd, Allerton Bywater, Castleford, WF10 2DB',
  interestRate: 11.9,
};
